### ISSUE TITLE
[2]. Удаление человека с детьми и супругами. 

### ISSUE THREAD

**Issue by alexglen** [ultrapotato69/genealogy-back#20]
Нужна возможность удалять людей с детьми и супругами, чтобы данные оставались консистентными, чтобы не было пустых ссылок в базе.

**Comment by ultrapotato69** [comment]
Удаление человека с детьми по сути уже реализовано. Если удалить ребенка или родителя, то каскадно удалится связь ребенок-родитель.
При удалении супруга добавлю ограничение, что поле spouseId второго супруга будет зануляться
